# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: duckonemorec
# "service" is the name of this project. This will also be added to your AWS resource names.
service: product-information-serverless

provider:
  name: aws
  runtime: nodejs20.x

plugins:
  - serverless-offline

functions:
  categories:
    handler: dist/apps/category/apps/category/src/serverless.handler
    events:
      - http:
          method: ANY
          path: /V1/categories/
      - http:
          method: ANY
          path: '/V1/categories/{proxy+}'

  products:
    handler: dist/apps/product/apps/product/src/serverless.handler
    events:
      - http:
          method: ANY
          path: /V1/products/
      - http:
          method: ANY
          path: '/V1/products/{proxy+}'

  attributes:
    handler: dist/apps/attribute/apps/attribute/src/serverless.handler
    events:
      - http:
          method: ANY
          path: /V1/attributes/
      - http:
          method: ANY
          path: '/V1/attributes/{proxy+}'